server:
  port: 8080
spring:
  application:
    name: "StudentsManager"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?prepareThreshold=0"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
